### PR TITLE
846 lattest session log

### LINKED ISSUE #846: SessionLogs/Latest
Currently tap creates a sessionlog every time it starts up, but the newest sessionlog always has a new name, making it harder than necessary to find it. I suggest we make either a symlink og a hardlink to the lattest sessionlog and save it in a SessionLog/Latest.txt file, so the latest session log is always easy to find.

### PR DESCRIPTION
**Pull request by frederikja163**
Create a hardlink to SessionLogs/Latest.txt for the latest sessionlog Should be useful when wanting to open the latest sessionlog without knowing what the name of the file is.

Closes #846

### CODE REVIEW

**Review by rmadsen-ks — CHANGES_REQUESTED** [review]
I think it looks awesome, but we could improve it a bit.

**Comment by frederikja163** [comment]
This should now work on Linux, Mac and Windows, however i havent been able to test on either Linux or Mac.

**Comment by alnlarsen** [comment]
This works on Linux. I will test on Mac when I get home.

**Comment by alnlarsen** [comment]
It works on Mac

**Review by alnlarsen — APPROVED** [review]
This looks good to me.

**Review by AsgerIversen — APPROVED** [review]

**Pull request merged**
