### PR TITLE
689 stop shipping netstandard

### LINKED ISSUE #689: Stop shipping netstandard.dll on Linux
It looks like we have been shipping some .net framework version of 'netstandard.dll' which consists entirely of `TypeForwardedTo(...)` implementations pointing to the .NET Framework 462 implementation. This is causing issues for some plugins, so let's just stop shipping it. 

I investigated why it is being shipped in the first place, and it looks like it is being copied to the output directory when we build the MSBuild SDK project.

### PR DESCRIPTION
**Pull request by alnlarsen**
Maybe this hardcoded solution isn't the best.

Closes #689

### CODE REVIEW

**Review by rmadsen-ks — APPROVED** [review]
Looks good!

**Comment by AsgerIversen** [comment]
@alnlarsen is this problem specific to netstandard.dll? I would imagine that if MSBuild put netstandard.dll in the output folder, it also put some other dlls there (some of the ones netstandard.dll forwards types to).

**Comment by alnlarsen** [comment]
@AsgerIversen I don't know. Removing netstandard.dll here is solving a concrete problem, but I think this is a pretty suspect fix, but in this case we know that netstandard.dll is **always** provided by the runtime.

It would be a good idea to launch an investigation and find a more general fix when we have the time.

**Comment by alnlarsen** [comment]
I prefer #791

**Pull request closed without merging**
