### PR TITLE
760 FileRepository PackageManager Supporting Uri: Fix

### LINKED ISSUE #760: Package Manager default settings not happy on Windows (file:///C:/Program%252520Files/OpenTAP)
I’m seeing a problem when I install OpenTAP 9.18.4 on Windows where the default Package Manager settings are throwing an error:

00:00:04.273 : Settings : Debug : No settings file exists for PackageManagerSettings. A new instance with default values has been created. [835 us]
00:00:04.285 : UpdateCheck : Warning : Update check against file:///C:/Program%252520Files/OpenTAP failed. See debug messages for details.
00:00:04.287 : UpdateCheck : Debug : DirectoryNotFoundException: File package repository directory not found at: file:///C:/Program%252520Files/OpenTAP
00:00:04.300 : UpdateCheck : Debug : at OpenTap.Package.FilePackageRepository.LoadPath(CancellationToken cancellationToken)
00:00:04.300 : UpdateCheck : Debug : at OpenTap.Package.FilePackageRepository.CheckForUpdates(IPackageIdentifier packages, CancellationToken cancellationToken)
00:00:04.300 : UpdateCheck : Debug : at OpenTap.Package.UpdateCheck.<>c__DisplayClass5_0.b__0(IPackageRepository repo)
00:00:04.304 : UpdateCheck : Debug : Exception caught at:
00:00:04.312 : UpdateCheck : Debug : at Void b__1()
00:00:04.312 : UpdateCheck : Debug : at Void InnerInvokeWithArg(System.Threading.Tasks.Task)
00:00:04.312 : UpdateCheck : Debug : at Void b__0(System.Object)
00:00:04.312 : UpdateCheck : Debug : at Void Execute()
00:00:04.312 : UpdateCheck : Debug : …

image
image
1568×186 51.2 KB
Another effect of this bug is that %TAP_PATH%\Settings\Package Manager.xml is never created.

A third effect is that I can’t install Packages in the Package Manager GUI. I have to install packages from the CLI.

This seems like a bug, maybe in the installer?

WORKAROUND:

- remove the goofy path via the Package Manager settings UI and save the settings
- reopen OpenTAP
- this seems to resolve all effects mentioned above

### PR DESCRIPTION
**Pull request by rmadsen-ks**
- Fixed the issue by unescaping the absolute path.
Close #760

### CODE REVIEW

**Comment by alnlarsen** [comment]
Looks like a good fix. I will test this in the PM GUI

**Comment by alnlarsen** [comment]
This doesn't seem to work. I have a good way to reproduce the issue. I will work on a fix

**Review by alnlarsen — APPROVED** [review]
I think this is the right approach

**Comment by alnlarsen** [comment]
This works for me in the package manager GUI now.

**Comment by rmadsen-ks** [comment]
Ok, it sounds like this should be merged then. (In addition to a fix on ks8400)

**Pull request merged**
